volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  pgdb:
    container_name: pgdb
    build:
      context: ./pgdb/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - public_network
      - private_network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s

  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://app_user:postgres@pgdb:5432/app_db
    networks:
      - public_network
      - private_network
    ports:
      - 8000:8000
