volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  pgdb:
    container_name: pgdb
    # image: simonangelfong/demo-ecs-svc-pgdb
    # image: pgdb
    build:
      context: ./pgdb/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - public_network
      - private_network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s

  # fastapi:
  #   container_name: fastapi
  #   image: simonangelfong/demo-ecs-svc-fastapi
  #   # image: fastapi
  #   # build:
  #     # context: ./fastapi/
  #     # dockerfile: Dockerfile
  #   environment:
  #     - ENV=dev
  #     - DEBUG=true
  #     - DATABASE__HOST=pgdb
  #     - DATABASE__PORT=5432
  #     - DATABASE__DB_NAME=app_db
  #     - DATABASE__USER=app_user
  #     - DATABASE__PASSWORD=postgres
  #   networks:
  #     - public_network
  #     - private_network
  #   ports:
  #     - 8000:8000
