volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  postgres:
    container_name: postgres
    build:
      context: ./pgdb/
      dockerfile: Dockerfile
    env_file:
      - fastapi/.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      # - public_network
      - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/dev.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2028M
        reservations:
          cpus: "0.5"
          memory: 1024M

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    networks:
      # - public_network
      - private_network
    ports:
      - "6379:6379"

  fastapi01:
    container_name: fastapi01
    # image: simonangelfong/demo-ecs-svc-fastapi
    # image: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - DEBUG=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_APP_USER=app_user
      - POSTGRES_APP_DB=app_db
      - POSTGRES_APP_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi02:
    container_name: fastapi02
    # image: simonangelfong/demo-ecs-svc-fastapi
    # image: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - DEBUG=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_APP_USER=app_user
      - POSTGRES_APP_DB=app_db
      - POSTGRES_APP_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi03:
    container_name: fastapi03
    # image: simonangelfong/demo-ecs-svc-fastapi
    # image: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - DEBUG=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_APP_USER=app_user
      - POSTGRES_APP_DB=app_db
      - POSTGRES_APP_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi04:
    container_name: fastapi04
    # image: simonangelfong/demo-ecs-svc-fastapi
    # image: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - DEBUG=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_APP_USER=app_user
      - POSTGRES_APP_DB=app_db
      - POSTGRES_APP_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public_network
      - private_network
    ports:
      - "8080:8080"
    depends_on:
      - fastapi01
      - fastapi02
      - fastapi03
      - fastapi04
