volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  pgdb:
    container_name: pgdb
    build:
      context: ./pgdb/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      - public_network
      # - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/dev.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2028M
        reservations:
          cpus: "0.5"
          memory: 1024M

  fastapi:
    container_name: fastapi
    # image: simonangelfong/demo-ecs-svc-fastapi
    # image: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - DEBUG=true
      - DATABASE__HOST=pgdb
      - DATABASE__PORT=5432
      - DATABASE__DB_NAME=app_db
      - DATABASE__USER=app_user
      - DATABASE__PASSWORD=postgres
    networks:
      - public_network
      - private_network
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
