name: "Delete API(Prod)"

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *"

# read write
permissions:
  contents: read
  id-token: write

# multiple trigger
concurrency:
  group: delete-prod-cd-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true # Cancel older runs

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: echo
  #       run: echo test


  delete_prod_cluster:
    name: Delete Cluster(Prod)
    runs-on: ubuntu-latest
    timeout-minutes: 90
    environment: api-prod
    env:
      TF_DIR: aws/infra/
      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_env: ${{ vars.ENV }}
      KUBE_DIR: kube/
      KUBE_CLUSTER_NAME: "${{ vars.PROJECT }}-${{ vars.APP }}-${{vars.ENV}}-eks"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Terraform plugin cache
        run: |
          mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
          echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}

      - name: Terraform init - S3 backend
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init -reconfigure -input=false \
            -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="key=${{ vars.PROJECT }}/${{vars.APP}}/${{ vars.ENV }}/terraform.tfstate" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform fmt -check -recursive -no-color
          terraform validate -no-color

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        id: plan
        run: terraform plan -out=tfplan-destroy -input=false -no-color -destroy

      - name: Show plan (JSON)
        working-directory: ${{ env.TF_DIR }}
        run: terraform show -json tfplan-destroy > tfplan-destroy.json

      - name: Save plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-bundle
          path: |
            ${{ env.TF_DIR }}/tfplan-destroy
            ${{ env.TF_DIR }}/tfplan-destroy.json
          retention-days: 3

      - name: Terraform Destroy
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -no-color tfplan-destroy

      # - name: Update kubeconfig
      #   run: aws eks update-kubeconfig --region ${{ env.TF_VAR_aws_region}} --name ${{ env.KUBE_CLUSTER_NAME}}

      # - name: Deploy to EKS
      #   run: |
      #     sed 's/-dev/-staging/' kube/04_fastapi.yaml
      #     sed 's/-dev/-staging/' kube/05_nginx.yaml
      #     kubectl apply -f ${{ env.KUBE_DIR }}

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>GitHub Actions CI/CD Notification</h2>
            <p><b>Project</b>: ${{ vars.PROJECT}}</p>
            <p><b>Application</b>: ${{ vars.APP}}</p>
            <p><b>Repository</b>: ${{ github.repository }}</p>
            <p><b>Env</b>: ${{ vars.ENV }}</p>
            <p><b>Job</b>: ${{ github.job }}</p>
            <p><b>Status</b>: ${{ job.status }}</p>
            <p><b>Branch</b>: ${{ github.ref }}</p>
            <p><b>Workflow</b>: ${{ github.workflow }}</p>
            <p><b>Commit</b>: ${{ github.sha }}</p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
